name: Test

on: [push, pull_request]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ["1.23", "1.24", "1.25"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: go test -v ./...
